In [157]:
import pandas as pd
import numpy as np
from category_encoders import TargetEncoder
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression  

In [158]:
n_rows=1000        #can generate random value
d={
    'Color' :np.random.choice(['red','green','blue','blue'],n_rows),'Size':np.random.choice(['large','medium','small'],n_rows),'Likes' :np.random.choice(['flower','insert','birds'],n_rows),'Target':np.random.choice([43,66,78,34],n_rows)
    }
df=pd.DataFrame(d)
df

# d={'col_1':['a','v','d','k'], 'col_2' :['red','green','blue','black'] ,'col_3' : ['fower','insert','birds','plants'],'Target':[43,66,78,34]}
# df=pd.DataFrame(d)
# df

,Color,Size,Likes,Target
0,blue,medium,insert,66
1,blue,small,flower,66
2,blue,small,birds,43
3,green,small,insert,78
4,blue,large,birds,66
...,...,...,...,...
995,blue,small,insert,66
996,green,small,flower,66
997,blue,small,flower,43
998,blue,large,insert,43


In [159]:
X=df.drop('Target',axis=1)
y=df['Target']  
# y=df.Target

In [160]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,train_size=0.8,random_state=42)

In [161]:
Label_encoder=LabelEncoder()


In [162]:
# updated_Xtrain=Label_encoder.fit_transform(Xtrain) 
# it accepts 1d but 2d is given
'''ValueError: y should be a 1d array, got an array of shape (800, 3) instead.'''

'ValueError: y should be a 1d array, got an array of shape (800, 3) instead.'

In [163]:
updated_Xtrain=Label_encoder.fit_transform(Xtrain['Color']) 
updated_Xtrain

array([0, 0, 1, 1, 2, 1, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 2, 2, 1, 2, 0,
       0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 2, 1, 0, 0, 2, 1, 0, 2, 1, 1, 2, 2,
       1, 0, 0, 0, 1, 0, 1, 2, 1, 0, 0, 1, 1, 1, 1, 0, 1, 2, 1, 0, 2, 2,
       2, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0,
       1, 0, 2, 0, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 2, 2, 2, 1, 0, 2, 0, 2, 2, 0, 0, 1, 0, 2, 0, 2, 2, 2, 2, 1, 0,
       0, 0, 0, 2, 0, 0, 0, 1, 0, 2, 2, 2, 1, 0, 1, 0, 1, 2, 0, 1, 0, 0,
       2, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 1, 1, 0, 0, 2, 0, 0, 2, 0, 2,
       1, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 2, 1, 0, 2, 2, 2, 0, 1, 0, 1, 1,
       1, 0, 2, 2, 2, 0, 1, 0, 0, 1, 2, 2, 0, 1, 2, 1, 2, 1, 1, 0, 0, 2,
       0, 1, 0, 1, 0, 0, 0, 2, 1, 1, 2, 0, 0, 1, 0, 2, 1, 0, 1, 0, 2, 1,
       0, 0, 0, 0, 2, 0, 0, 2, 0, 1, 2, 0, 0, 2, 1, 0, 2, 0, 2, 2, 0, 0,
       2, 2, 2, 2, 0, 2, 0, 0, 1, 2, 1, 0, 2, 1, 0, 2, 2, 1, 1, 2, 0, 0,
       1, 0, 1, 2, 1, 2, 0, 0, 1, 0, 0, 1, 0, 1, 1,

In [164]:
updated_Xtest=Label_encoder.transform(Xtest['Color'])
updated_Xtest

array([0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 2, 0, 1, 0, 1, 2, 2, 1, 1, 2,
       1, 0, 0, 1, 2, 0, 0, 0, 0, 1, 0, 1, 2, 2, 0, 0, 0, 1, 0, 2, 2, 1,
       0, 2, 0, 1, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 2, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 2, 1, 1, 2, 1, 0, 0, 1, 0, 1, 2, 0, 0, 1, 1, 0, 0, 0,
       2, 1, 1, 2, 0, 1, 0, 0, 1, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 2, 0, 2,
       0, 0, 0, 0, 1, 2, 0, 2, 1, 1, 2, 0, 1, 0, 0, 1, 0, 0, 0, 1, 2, 0,
       0, 0, 2, 0, 1, 0, 0, 2, 2, 0, 0, 0, 0, 0, 1, 0, 2, 2, 0, 1, 1, 0,
       0, 2, 2, 0, 2, 2, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2,
       2, 0, 0, 2, 1, 2, 0, 0, 2, 1, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2,
       0, 0])

In [165]:
# #new input
# new_input=['red','red','white']    #if all the values present it will transform  else error
# Label_encoder.transform(new_input)

### One Hot Encoder

In [166]:
One_hot_encoder=OneHotEncoder(handle_unknown='ignore',sparse_output=False)

Scenario-1: (without passing parameter)

we have to use toarray --> to get the binary o/p

scenario -2: (using Sparse_output)

sparse_output=False 

it will return the array directly when False given

sparse_output=True(by default)

it will return sparse matrix compressed when True is used

In [167]:
One_hot_encoder.fit_transform(Xtrain)
# dont use directly it will give sparse 

array([[1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.]])

In [168]:
#this is row values
values=One_hot_encoder.fit_transform(Xtrain)
# values.toarray()

In [169]:
One_hot_encoder.get_feature_names_out()

array(['Color_blue', 'Color_green', 'Color_red', 'Size_large',
       'Size_medium', 'Size_small', 'Likes_birds', 'Likes_flower',
       'Likes_insert'], dtype=object)

In [197]:
#this gives the column values or name
cols=One_hot_encoder.get_feature_names_out()

In [199]:
pd.DataFrame(values)

,0,1,2,3,4,5,6,7,8
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...
795,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
796,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
797,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
798,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0


In [172]:
#Invalid syntax
# One_hot_encoder.transform(Xtest[['Color','Size']])

'''ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Likes'''

'ValueError: The feature names should match those that were passed during fit.\nFeature names seen at fit time, yet now missing:\n- Likes'

In [173]:
#Valid syntax
One_hot_encoder.transform(Xtest)   

array([[1., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.]])

In [174]:
'''Invalid Syntax'''
# new_input=[['red'],['large']]
# One_hot_encoder.transform(new_input)

'''ValueError: X has 1 features, but OneHotEncoder is expecting 3 features as input.'''

'ValueError: X has 1 features, but OneHotEncoder is expecting 3 features as input.'

#### to check the no of rows

len(var)

#### To check no of column len(l[0])

In [175]:
len([['red'],['large']])   #rows

2

In [176]:
# new_input=[['red','large'] , ['blue','small']]
# One_hot_encoder.transform(new_input)
'''ValueError: X has 2 features, but OneHotEncoder is expecting 3 features as input.'''

'ValueError: X has 2 features, but OneHotEncoder is expecting 3 features as input.'

In [177]:
new_input=[['red','large','insert'] , ['blue','small','flower']]
One_hot_encoder.transform(new_input)

'''ValueError: Found unknown categories ['blue', 'red'] in column 0 during transform'''

C:\Users\ANUSHA C\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


"ValueError: Found unknown categories ['blue', 'red'] in column 0 during transform"

In [178]:
new_input=[['red','large','butterfly'] , ['blue','small','flower']]
One_hot_encoder.transform(new_input)
# 0., 0., 0. --> unknown value

C:\Users\ANUSHA C\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 1., 0.]])

In [179]:
One_hot_encoder.get_feature_names_out()

array(['Color_blue', 'Color_green', 'Color_red', 'Size_large',
       'Size_medium', 'Size_small', 'Likes_birds', 'Likes_flower',
       'Likes_insert'], dtype=object)

### Ordinal Encoder

In [180]:
ord_encoder=OrdinalEncoder()
updated_Xtrain=ord_encoder.fit_transform(Xtrain)
updated_Xtrain
'''
updated_Xtrain=ord_encoder.fit_transform(Xtrain['Color'])
ValueError: 
Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.
'''

"\nupdated_Xtrain=ord_encoder.fit_transform(Xtrain['Color'])\nValueError: \nExpected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.\n"

In [181]:
ord_encoder.get_feature_names_out()

array(['Color', 'Size', 'Likes'], dtype=object)

In [182]:
updated_Xtest=ord_encoder.transform(Xtest)

'''updated_Xtest=ord_encoder.transform(Xtest['Color'])
ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. 
Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead'''

"updated_Xtest=ord_encoder.transform(Xtest['Color'])\nValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. \nPass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead"

### unknown value 

In [183]:
new_input=([['red1','medium','insect'],['orange','medium','insect'],['red','medium','insect']])

In [184]:
'''ord_encoder.transform(new_input)'''
'''ValueError: Found unknown categories ['orange', 'red1'] in column 0 during transform'''

"ValueError: Found unknown categories ['orange', 'red1'] in column 0 during transform"

In [185]:
ord_encoder=OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1)
updated_Xtrain=ord_encoder.fit_transform(Xtrain)
updated_Xtest=ord_encoder.transform(Xtest)

new_data=pd.DataFrame(data=[['white','small','birds'],['red','medium','flower']],columns=['Color','Size','Likes'])
updated_new_data=ord_encoder.transform(new_data)
updated_new_data

array([[-1.,  2.,  0.],
       [ 2.,  1.,  1.]])

### Ordinal Encoder

In [186]:
ord_encoder=OrdinalEncoder(categories=[['red1','green','blue'],['large','small','medium'],['flower','insert','birds']],handle_unknown="use_encoded_value",unknown_value=-1)


In [187]:
#with order

# ord_encoder=OrdinalEncoder(categories=[['large','small','medium'],['red1','green','blue'],['insert','birds','flower']],handle_unknown="use_encoded_value")

'''TypeError: unknown_value should be an integer or np.nan when handle_unknown is 'use_encoded_value', got None.'''

"TypeError: unknown_value should be an integer or np.nan when handle_unknown is 'use_encoded_value', got None."

In [188]:
# ord_encoder.fit_transform(Xtrain)
'''ValueError: Found unknown categories ['blue', 'green', 'red'] in column 0 during fit
'''

"ValueError: Found unknown categories ['blue', 'green', 'red'] in column 0 during fit\n"

In [189]:
ord_encoder.fit_transform(Xtrain)   #Transform accepts 2D
ord_encoder.transform(Xtest)

array([[ 2.,  2.,  2.],
       [ 1.,  1.,  1.],
       [ 1.,  0.,  2.],
       [ 1.,  2.,  2.],
       [ 2.,  2.,  1.],
       [ 1.,  1.,  1.],
       [ 2.,  2.,  1.],
       [ 1.,  2.,  2.],
       [ 2.,  2.,  0.],
       [ 2.,  1.,  2.],
       [ 2.,  1.,  2.],
       [ 2.,  2.,  0.],
       [-1.,  0.,  1.],
       [ 2.,  2.,  2.],
       [ 1.,  0.,  2.],
       [ 2.,  0.,  2.],
       [ 1.,  0.,  0.],
       [-1.,  2.,  2.],
       [-1.,  0.,  0.],
       [ 1.,  1.,  0.],
       [ 1.,  2.,  1.],
       [-1.,  2.,  2.],
       [ 1.,  0.,  1.],
       [ 2.,  0.,  0.],
       [ 2.,  2.,  1.],
       [ 1.,  0.,  0.],
       [-1.,  0.,  2.],
       [ 2.,  0.,  1.],
       [ 2.,  1.,  0.],
       [ 2.,  1.,  1.],
       [ 2.,  0.,  1.],
       [ 1.,  1.,  1.],
       [ 2.,  2.,  1.],
       [ 1.,  0.,  0.],
       [-1.,  2.,  1.],
       [-1.,  2.,  1.],
       [ 2.,  2.,  1.],
       [ 2.,  1.,  0.],
       [ 2.,  2.,  1.],
       [ 1.,  0.,  1.],
       [ 2.,  2.,  2.],
       [-1.,  1.

### TO select only object column



In [ ]:
# ocj_col=[]  #wrong
obj_cols=Xtrain.select_dtypes(include='object').columns


# for the numerical
nums_cols=Xtrain.select_dtypes(include=int).columns

### Target Encoder

In [191]:
from category_encoders import TargetEncoder


In [192]:
#here we hav only passed color so onlt avg fro target col will be applied only to color column
tar_encoder=TargetEncoder(cols=['Color'], handle_unknown='values')   
tar_encoder.fit_transform(Xtrain,ytrain)

,Color,Size,Likes
29,55.08399,small,birds
535,55.08399,large,flower
695,53.69863,medium,birds
557,53.69863,small,insert
836,57.56000,small,flower
...,...,...,...
106,55.08399,large,birds
270,57.56000,small,flower
860,55.08399,small,flower
435,55.08399,medium,birds


In [193]:
tar_encoder.transform(Xtest)

,Color,Size,Likes
521,55.08399,medium,birds
737,53.69863,small,insert
740,53.69863,large,birds
660,53.69863,medium,birds
411,55.08399,medium,insert
...,...,...,...
408,55.08399,medium,flower
332,55.08399,small,flower
208,57.56000,medium,insert
613,55.08399,medium,flower


#### Wrong approach

In [194]:
# new_input=[['red','small','insert1']]
# tar_encoder.transform(new_input)

'''KeyError: 'Color' '''
#because we have mentioned the column to take average not the vlaues and while passing the input we have passed values aanf not mentioned the column names

"KeyError: 'Color' "

### correct approach

In [195]:
new_input=pd.DataFrame({'Color':['red'],'Size':['small'],'Likes':['flower']})

tar_encoder.transform(new_input)


,Color,Size,Likes
0,57.56,small,flower
